terminate called after throwing an instance of 'std::bad_function_call'
  what():  bad_function_call
/home/runner/work/_temp/81246fa8-e1fc-4681-a3f4-b27f8e370030.sh: line 1:  9469 Aborted                 (core dumped) Rscript testthat.R
##[error]Process completed with exit code 134.
